[template]
cargo_generate_version = ">=0.21.0"
exclude = [
    "target",
    "test-*",
    ".git",
    ".github",
    "LICENSE",
    "README.md",
    "install.sh",
    "Cargo.toml",
]

# Note: 'name' is handled automatically by cargo-generate as the project name
# We don't need to define it as a placeholder

[placeholders.author]
prompt = "Author name"
type = "string"
default = "Your Name"

[placeholders.email]
prompt = "Author email"
type = "string"
default = "you@example.com"

[placeholders.description]
prompt = "Project description"
type = "string"
default = "A new Axum web service"

[conditional.'crud_example'.placeholders]
crud_example = { type = "bool", prompt = "Include CRUD example API?", default = true }

[hooks]
pre = ["fix.rhai"]
