name: Template Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-template:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-generate
      run: cargo install cargo-generate
    
    - name: Validate cargo-generate.toml
      run: |
        if [ ! -f "cargo-generate.toml" ]; then
          echo "Error: cargo-generate.toml not found"
          exit 1
        fi
        echo "✅ cargo-generate.toml exists"
    
    - name: Test template generation
      run: |
        # Generate a project from the template
        cargo generate --path . --name test-project --silent \
          --define author="Test Author" \
          --define email="test@example.com" \
          --define description="Test project"
        
        # Enter generated project directory
        cd test-project
        
        # Check if Cargo.toml was generated correctly
        if ! grep -q 'name = "test-project"' Cargo.toml; then
          echo "Error: Project name not correctly substituted"
          exit 1
        fi
        
        echo "✅ Template variables substituted correctly"
    
    - name: Build generated project
      run: |
        cd test-project
        
        # Copy example config if needed
        if [ -f config/services-example.toml ]; then
          cp config/services-example.toml config/services.toml
        fi
        
        # Build the generated project
        cargo build --verbose
        
        echo "✅ Generated project builds successfully"
    
    - name: Run tests on generated project
      run: |
        cd test-project
        cargo test --verbose
        
        echo "✅ Generated project tests pass"
    
    - name: Check clippy on generated project
      run: |
        cd test-project
        cargo clippy -- -D warnings
        
        echo "✅ Generated project passes clippy"